### PR TITLE
Fix issues related to line endings

### PR DESCRIPTION
**Pull request by tprobinson**
Paths were being parsed with '\r' on the end, causing FileNotFound.
The initial ADB command was also not working without the -x flag. (I'm unsure why, as the `su -c` was returning 0)

I tested this with Authy and Steam on the same device, and it all worked out.
However, the generated QR code for Steam didn't work, I had to enter its details manually.

### CODE REVIEW

**Comment by puddly** [comment]
That's odd. What phone and platform are you running the script on?

**Comment by tprobinson** [comment]
LG V20, h990DS, on a custom Oreo ROM. My computer's OS is Linux, Manjaro specifically

**Comment by puddly** [comment]
Thanks for the fix. Your changes to `SingleBinaryADBInterface.list_dir` actually break AndOTP exporting for me, specifically [where that function now returns a list of `bytes`](https://github.com/puddly/android-otp-extractor/pull/24/commits/af3b36584b424fc35f45da2184a5a8f7d5ac29d2#diff-e4fab554c3d1579d12b9deac55171d64R200) instead of a list of `pathlib.PurePosixPath` objects.

If you replace your changes aside from the `-x` flag with the following, do things still work?

             return [path/l.rstrip(b'\r\n').decode('utf-8') for l in lines]

I'm curious to know why you're seeing carriage return characters. Are you using a standard build of `adb`?

**Comment by tprobinson** [comment]
Oops, sorry I didn't reply to this for a while.

As far as I know, it's a standard build of ADB. Manjaro might have something weird going on, I'll try it out on Ubuntu (as-is, with my fix, and your fix) and let you know.

**Comment by puddly** [comment]
I'm just going to push a fix for this just in case. I don't consider the possibility of application files existing with whitespace at the end so it shouldn't pose an issue.

**Pull request closed without merging**
