### PR TITLE
Fix `ls /` line reader end detection

### PR DESCRIPTION
**Pull request by sebastianst**
With the old logic, it never printed the weird `sentinel` for me, so it just threw the `ValueError` instead of returning... I changed it instead to `echo __end__` and detect that `__end__` token. There will probably never be a file called `__end__` in your phone's root directory...

### CODE REVIEW

**Comment by puddly** [comment]
I completely forgot about using `echo` so thanks for the fix.

What device is this on? Could you change `__end__` to some other random value (like I had) so there's virtually no chance of a collision?

**Comment by sebastianst** [comment]
OK did it.
That's on a Pixel 2, rooted stock rom.

**Comment by puddly** [comment]
Looks good to me, thanks.

I'd like to see why my original approach didn't work on a Pixel 2, though, so more glitches like this don't happen. What exact version of Android are you running on it?

**Comment by sebastianst** [comment]
Thanks for merging.
It's running Android 9.

**Pull request merged**
