### PR TITLE
Avoid exceptions for accounts without a name

### PR DESCRIPTION
**Pull request by paour**
These were probably generated by an older version of Google Authenticator on my device.

### CODE REVIEW

**Comment by puddly** [comment]
Thanks for the bug report. Can you check if the `email` column contains a valid name? It could be that the account you imported into Google Authenticator just did not have a name and Authenticator never set one. In that case, I think populating the account name from the `email` column as a fallback might be a better solution

**Comment by puddly** [comment]
Thanks.

**Comment by paour** [comment]
Indeed, the `email` column contains better data, I've pushed a commit that makes use of it. Since this new commit essentially reverts the previous one, feel free to merge squash. Oops, you were faster :-)

**Comment by paour** [comment]
And thank you for a very useful tool! And a very nice hack :-)

**Pull request merged**
